version: "3.8"

services:
  # 1. Base de datos Cache
  redis:
    container_name: redis-cache
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  # 2. Tu API Spring Boot
  backend:
    container_name: consulta-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Conexión a Redis (nombre del servicio de arriba)
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - redis
    restart: always

  # 3. Tu Frontend React
  frontend:
    container_name: consulta-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Accederás por localhost:3000
    depends_on:
      - backend
    restart: always